steps:
  - label: ':drum_with_drumsticks: Node + DB sync :drum_with_drumsticks:'
    commands:
      - >
        nix develop --accept-flake-config .#python --command
        pytest sync_tests/tests/ -m "node_sync or db_sync"
        --environment "${environment}"
        --node-revision "${node_version}"
        --db-sync-revision "${db_sync_version}"
        --db-sync-start-options "${db_sync_start_arguments}"
    timeout_in_minutes: 14400
    artifact_paths:
      - "sync_logs.zip"
      - "sync_results.zip"
      - "monitor.zip"
    agents:
      system: x86_64-linux
      queue: "${queue_name:-core-tech-bench}"
