steps:
  - label: ':drum_with_drumsticks: Run the Cardano node sync test on Mainnet using a Linux machine'
    commands:
      - >
        nix develop --accept-flake-config .#python --command
        pytest sync_tests/tests/test_nodesync_artifacts.py
        --environment "${env}"
        --node-revision "${tag_no1}"
    timeout_in_minutes: 14400
    agents:
      system: x86_64-linux
      queue: "${queue_name:-core-tech-bench}"
    artifact_paths:
      - "sync_logs.zip"
      - "sync_results.zip"
      - "monitor.zip"
