name: Nightly node sync tests

on:
  schedule:
    - cron: '0 23 * * *'  # Every day at 23:00 UTC
  workflow_dispatch:

jobs:
  nightly_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout cardano-sync-tests repository
        uses: actions/checkout@v4
        with:
          path: cardano_sync_tests
          ref: ${{ github.ref_name }}

      - name: Trigger Buildkite pipeline for Mainnet sync tests
        uses: 'buildkite/trigger-pipeline-action@v1.5.0'
        env:
          BUILDKITE_API_ACCESS_TOKEN: ${{ secrets.BUILDKITE_API_ACCESS_TOKEN }}
          PIPELINE: 'input-output-hk/node-sync-tests'
          BRANCH: ${{ github.ref_name }}
          MESSAGE: ':github: Triggered by GitHub Action'

          # Database secrets
          AWS_DB_USERNAME: ${{ secrets.AWS_DB_USERNAME }}
          AWS_DB_PASS: ${{ secrets.AWS_DB_PASS }}
          AWS_DB_NAME: ${{ secrets.AWS_DB_NAME }}
          AWS_DB_HOSTNAME: ${{ secrets.AWS_DB_HOSTNAME }}

          # Blockfrost API
          BLOCKFROST_API_KEY: ${{ secrets.BLOCKFROST_API_KEY }}

      - name: Finalize sync
        run: echo "Sync job finished."
